### ISSUE TITLE
Picture in markdown

### ISSUE THREAD

**Issue by Mindavi** [M1ND-B3ND3R/BoopSuite#1]
You might want to re-add the picture, and I think it would be a good idea if you put some meaningful alt text if the image happens to break.
![broken image in markdown, showing alt text](https://cloud.githubusercontent.com/assets/9799623/26296271/3af79f42-3ece-11e7-8a24-256b2907f962.PNG)

**Comment by M1ND-B3ND3R** [comment]
WOOOH my first issue, thanks for submitting, Tomorrow I will upload some images and add better alt tags! Thanks for submitting.
