### ISSUE TITLE
Installation of requirements fails on Fedora 25

### ISSUE THREAD

**Issue by etem** [M1ND-B3ND3R/BoopSuite#5]
Hello, 

I get the following output when I try to install the requirements via pip on Fedora 25 : 

➜  BoopSuite git:(master) sudo pip install -r requirements.txt

[sudo] password for bavarian: 
Collecting pyric (from -r requirements.txt (line 1))
  Downloading PyRIC-0.1.6.3.tar.gz (870kB)
    100% |████████████████████████████████| 880kB 1.3MB/s 
Collecting netaddr (from -r requirements.txt (line 2))
  Downloading netaddr-0.7.19-py2.py3-none-any.whl (1.6MB)
    100% |████████████████████████████████| 1.6MB 780kB/s 
Collecting scapy (from -r requirements.txt (line 3))
  Downloading scapy-2.3.3.tgz (1.4MB)
    100% |████████████████████████████████| 1.4MB 920kB/s 
Collecting tabulate (from -r requirements.txt (line 4))
  Downloading tabulate-0.7.7-py2.py3-none-any.whl
Collecting pyx (from -r requirements.txt (line 5))
  Downloading PyX-0.14.1.tar.gz (2.5MB)
    100% |████████████████████████████████| 2.5MB 432kB/s 
**No files/directories in /tmp/pip-build-dTSwms/pyx/pip-egg-info (from PKG-INFO)**

Looks like pip cannot install PyX but I couldn't figure out how to fix this. 

➜  BoopSuite git:(master) sudo pip install pyx
Collecting pyx
  Using cached PyX-0.14.1.tar.gz
****No files/directories in /tmp/pip-build-J5Ydlr/pyx/pip-egg-info (from PKG-INFO)****

**Comment by M1ND-B3ND3R** [comment]
Ok, so looks like thats an old dependency that I can remove so I am pulling it out and take a look at the CHANGELOG I gave credit where it is due for the find. Thanks. :)

**Comment by skuxy** [comment]
Hey, it's still spewing same error as for @etem for me :)

**Comment by M1ND-B3ND3R** [comment]
I commited a new fix so it shouldn't be... can you reclone and post a screenshot if its still happening?

**Comment by skuxy** [comment]
Oi, nevermind, issue on my side. Sorry!

Installs with absolutely no problems :)

**Comment by M1ND-B3ND3R** [comment]
Awesome :)

**Comment by etem** [comment]
Thank you! Installation works perfectly now. 
There are some issues with GUI version of the program but I've opened issue #6 for that.
